---
# tasks file for passbolt_start
- name: Docker-compose up
  community.docker.docker_compose:
    project_src: /home/ansible/passbolt/

- name: Wait for 25 seconds
  ansible.builtin.pause:
    seconds: 25

- name: Register Passbolt user
  become: true
  ansible.builtin.command: "docker exec passbolt_passbolt_1 su -m -c 'bin/cake passbolt register_user -u {{ email }} -f {{ firstname }} -l {{ last_name }} -r admin' -s /bin/sh www-data"
  register: passbolt_user_registration

# - name: Display passbolt_user_registration variable
#   ansible.builtin.debug:
#     var: passbolt_user_registration

- name: Display output
  ansible.builtin.debug:
      msg: "{{ passbolt_user_registration.stdout_lines | select('match', '^(https?://).*') | list }}"
