---
- name: Update serverpark
  ansible.builtin.package:
    name: "*"
    state: latest
  become: true

- name: Install Neovim
  ansible.builtin.apt:
    name: neovim
    state: present
  when: ansible_distribution in ["Debian", "Ubuntu"]

- name: Install vim
  ansible.builtin.dnf:
    name: vim-enhanced
    state: present
  when: ansible_distribution == "Fedora"

- name: Install Chrony
  ansible.builtin.package:
    name: chrony
    state: latest

- name: Change timezone
  community.general.timezone:
    name: "{{ timezone }}"
  notify: Restart Chrony service

